author:
  email: tikismoke@users.noreply.github.com
  homepage: https://github.com/tikismoke/home-assistant-plcbus
  name: Tikismoke
description: plcbus integration
files:
  - custom_components/plcbus/__init__.py
  - custom_components/plcbus/switch.py
  - custom_components/plcbus/lib/PLCBusSerialHandler.py
  - custom_components/plcbus/lib/__init__.py
  - custom_components/plcbus/lib/plcbus_lib.py
keywords:
  - plcbus
  - switch
  - homeassistant
  - home-assistant
  - custom-component
  - python
license: MIT License
name: switch.plcbus
type: component
